#!/usr/bin/env bash
# HIVEMIND × NotebookLM — one-shot installer
# Run: curl -fsSL https://hivemind.davinciai.eu/install/notebooklm.sh | bash
#
# NotebookLM doesn't accept HTTP MCP directly. We install a local stdio
# bridge script that proxies stdio → HTTP via `mcp-remote`.
# User configures NotebookLM to spawn the bridge script.

set -euo pipefail

INSTALLER_BASE="${INSTALLER_BASE:-https://hivemind.davinciai.eu/install}"
COMMON_LIB="${COMMON_LIB:-$INSTALLER_BASE/installer-common.sh}"

if [ -f "./installer-common.sh" ]; then
  source ./installer-common.sh
else
  source <(curl -fsSL "$COMMON_LIB")
fi

header "NotebookLM (local bridge)"

step "Detecting OS..."
detect_os
ok "OS: $OS ($ARCH)"

check_prereqs
require_cmd node
require_cmd npx

prompt_for_key
validate_key

# ──────────────────────────────────────────────────────────────────────
# Install bridge launcher script to ~/.hivemind/notebooklm-bridge.sh
# ──────────────────────────────────────────────────────────────────────
BRIDGE_DIR="${HOME}/.hivemind"
BRIDGE_PATH="${BRIDGE_DIR}/notebooklm-bridge.sh"
mkdir -p "$BRIDGE_DIR"

step "Installing local stdio→HTTP bridge..."
cat > "$BRIDGE_PATH" <<EOF
#!/usr/bin/env bash
# HIVEMIND NotebookLM bridge — autogenerated by installer
# Proxies stdio MCP calls from NotebookLM → HTTP MCP at HIVEMIND core.
exec npx -y mcp-remote "$HIVEMIND_MCP_URL" --header "Authorization: Bearer $HIVEMIND_KEY"
EOF

chmod +x "$BRIDGE_PATH"
ok "Bridge script: $BRIDGE_PATH"

# Sanity test
step "Testing bridge spawn (3s)..."
if timeout 3 bash "$BRIDGE_PATH" <<<'' 2>&1 | head -c 100 | grep -q "jsonrpc\|mcp-remote\|InitializeResult" 2>/dev/null; then
  ok "Bridge launches successfully"
else
  warn "Could not confirm bridge boot — first run may take longer (npm install)"
fi

# ──────────────────────────────────────────────────────────────────────
# Print NotebookLM config instructions (manual final step)
# ──────────────────────────────────────────────────────────────────────
echo ""
echo "${C_BOLD}NotebookLM setup (final manual step):${C_RESET}"
echo ""
echo "  1. Open NotebookLM Desktop / Web"
echo "  2. Go to Settings → Tools/MCP → Add server"
echo "  3. Server type: ${C_BOLD}stdio (local command)${C_RESET}"
echo "  4. Command: ${C_BOLD}${BRIDGE_PATH}${C_RESET}"
echo "  5. Name: ${C_BOLD}hivemind${C_RESET}"
echo "  6. Save → reconnect → HIVEMIND tools appear"
echo ""

record_install "notebooklm" "$BRIDGE_PATH"
print_success_footer "NotebookLM"
