export const davinciTestConfig = {
  config: {
    tenantId: 'davinci',
    tenantName: 'DAVINCI AI',
    agentId: 'davinci',
    agentName: 'DAVINCI AI',
    language: 'de',
    wsBaseUrl: 'wss://demo.davinciai.eu:8030/ws',
  },
  brand: {
    name: 'DAVINCI AI',
    label: 'Voice Agent Test',
    eyebrow: 'Main Website Testing',
    accent: '#CADCFC',
    accentSoft: '#A0B9D1',
    surface: '#121212',
    surfaceSoft: '#171717',
    backgroundA: '#141111',
    backgroundB: '#221d1d',
    text: '#F5F5F5',
    textMuted: 'rgba(245, 245, 245, 0.62)',
    orbPrimary: '#CADCFC',
    orbSecondary: '#A0B9D1',
  },
};

export const bundbTestConfig = {
  config: {
    tenantId: 'bundb',
    tenantName: 'BUNDB',
    agentId: 'bundb',
    agentName: 'BUNDB Agent',
    language: 'de',
    wsBaseUrl: 'wss://demo.davinciai.eu:8030/ws',
  },
  brand: {
    name: 'BUNDB',
    label: 'Client Test Page',
    eyebrow: 'Main Website Testing',
    accent: '#CADCFC',
    accentSoft: '#A0B9D1',
    surface: '#121212',
    surfaceSoft: '#171717',
    backgroundA: '#141111',
    backgroundB: '#221d1d',
    text: '#F5F5F5',
    textMuted: 'rgba(245, 245, 245, 0.62)',
    orbPrimary: '#CADCFC',
    orbSecondary: '#A0B9D1',
  },
};
