import React, { useEffect, useState } from 'react';
import apiClient from '../shared/api-client';

const labels = {monthlyCredits:'Included credits',maxUsers:'Team seats',maxProjects:'Projects',maxConnectors:'Connected apps',maxMemories:'Memory capacity',llmTokensPerMonth:'Monthly model tokens',searchQueriesPerDay:'Daily searches',searchQueriesPerMonth:'Monthly searches',knowledgeBasePagesPerDay:'Daily knowledge pages',knowledgeBasePagesPerMonth:'Monthly knowledge pages',deepResearchPerDay:'Daily research jobs',deepResearchPerMonth:'Monthly research jobs',webIntelPerDay:'Daily Web Intel jobs',meetingMinutesPerMonth:'Monthly meeting minutes',hyperAgentRunsPerDay:'Daily HyperAgent runs',hyperAgentRunsPerMonth:'Monthly HyperAgent runs',taraTalkSecondsPerDay:'Daily voice seconds',taraTalkSecondsPerMonth:'Monthly voice seconds',agentSwarm:'Agent Swarm',cognitiveDreaming:'Company dreaming'};
const display = value => value === -1 ? 'Unlimited' : Number(value ?? 0).toLocaleString();
export default function OrganizationSettingsPanel() {
 const [organizations,setOrganizations]=useState([]),[orgId,setOrgId]=useState(''),[settings,setSettings]=useState(null),[limits,setLimits]=useState({}),[features,setFeatures]=useState({}),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const apply = next => {setSettings(next);setLimits({...next.overrides.limits});setFeatures({...next.overrides.features});setReason('');};
 useEffect(()=>{let cancelled=false;apiClient.listPlatformOrganizations().then(result=>{if(cancelled)return;setOrganizations(result.organizations??[]);setOrgId(result.organizations?.[0]?.id??'');}).catch(e=>{if(!cancelled)setError(e.response?.data?.error??'Organizations are unavailable.');});return()=>{cancelled=true;};},[]);
 useEffect(()=>{if(!orgId)return undefined;let cancelled=false;setBusy(true);setSettings(null);setError('');setNotice('');apiClient.getPlatformOrganizationSettings(orgId).then(result=>{if(!cancelled)apply(result.settings);}).catch(e=>{if(!cancelled)setError(e.response?.data?.error??'Organization settings are unavailable.');}).finally(()=>{if(!cancelled)setBusy(false);});return()=>{cancelled=true;};},[orgId]);
 const save=async event=>{event.preventDefault();if(!settings||busy)return;setBusy(true);setError('');setNotice('');try{const normalizedLimits=Object.fromEntries(Object.entries(limits).map(([key,value])=>[key,value===''||value===null?null:Number(value)]));const normalizedFeatures=Object.fromEntries(Object.entries(features).map(([key,value])=>[key,value===''||value===null?null:value===true||value==='true']));const result=await apiClient.updatePlatformOrganizationSettings(orgId,{revision:settings.revision,limits:normalizedLimits,features:normalizedFeatures,reason});apply(result.settings);setNotice('Settings saved. New work uses these effective limits.');}catch(e){setError(e.response?.data?.error??'Settings could not be saved.');}finally{setBusy(false);}};
 return <section id="admin-organizations" className="mb-6 scroll-mt-20 rounded-xl border border-[#e3e0db] bg-white p-5">
  <h2 className="text-lg font-semibold">Organizations</h2><p className="mt-1 text-sm text-[#737373]">Configure one organization without changing its plan, billing history or other organizations.</p>
  <label className="mt-4 block text-sm font-medium">Organization<select aria-label="Organization settings account" disabled={busy} value={orgId} onChange={e=>setOrgId(e.target.value)} className="mt-1 block w-full max-w-lg rounded-lg border p-2">{organizations.map(org=><option key={org.id} value={org.id}>{org.name}</option>)}</select></label>
  {error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}{notice&&<p role="status" className="mt-3 text-sm text-emerald-700">{notice}</p>}{busy&&!settings&&<p role="status" className="mt-4 text-sm">Loading organization settings…</p>}
  {settings&&settings.effective.overridesActive===false&&<p className="mt-3 text-sm text-amber-700">Organization overrides remain saved, but do not reactivate expired, revoked or suspended access.</p>}
  {settings&&<form onSubmit={save} className="mt-5 space-y-5">
   <div className="grid grid-cols-2 gap-3 lg:grid-cols-5">{[['Members',settings.usage.members],['Pending invitations',settings.usage.pendingInvites],['Included credits',settings.usage.credits.included],['Used credits',settings.usage.credits.used],['Remaining credits',settings.usage.credits.remaining]].map(([label,value])=><div key={label} className="rounded-lg bg-[#faf9f4] p-3"><p className="text-xs text-[#737373]">{label}</p><p className="mt-1 text-lg font-semibold">{display(value)}</p></div>)}</div>
   <p className="text-xs text-[#737373]">Credits are a shared {settings.usage.credits.credit_pool==='grant_lifetime'?'grant-lifetime':'monthly'} allowance. Remaining credits deduct historical usage and reservations. Changing the allowance does not erase usage or grant new permissions. Reserved: {display(settings.usage.credits.reserved)}. {settings.effective.entitlement?.effectiveUntil&&`Access ends ${new Date(settings.effective.entitlement.effectiveUntil).toLocaleString()}.`}</p>
   <details className="text-sm"><summary className="cursor-pointer font-medium">Current monthly usage</summary><dl className="mt-3 grid gap-2 sm:grid-cols-3">{[['Searches',settings.usage.monthly.searchQueries],['Knowledge pages',settings.usage.monthly.knowledgeBasePages],['HyperAgent runs',settings.usage.monthly.hyperAgentRuns],['Research jobs',settings.usage.monthly.deepResearchJobs],['Web Intel jobs',settings.usage.monthly.webIntelJobs],['Voice seconds',settings.usage.monthly.taraSeconds]].map(([label,value])=><div key={label}><dt className="text-xs text-[#737373]">{label}</dt><dd>{display(value)}</dd></div>)}</dl></details>
   <fieldset disabled={busy}><legend className="font-semibold">Limits</legend><p className="mb-3 mt-1 text-xs text-[#737373]">Leave blank to follow the plan or active grant. Use -1 for unlimited; 0 stops new usage. A seat limit must cover members and pending invitations.</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{settings.editable.limits.map(key=><label key={key} className="text-sm">{labels[key]??key}<input aria-label={labels[key]??key} type="number" step="1" min="-1" value={limits[key]??''} placeholder={`Inherited: ${display(settings.effective.inheritedLimits[key])}`} onChange={e=>setLimits({...limits,[key]:e.target.value})} className="mt-1 block w-full rounded-lg border p-2"/><span className="text-xs text-[#737373]">Effective: {display(settings.effective.limits[key])}</span></label>)}</div></fieldset>
   <fieldset disabled={busy}><legend className="font-semibold">Supported capabilities</legend><div className="mt-3 grid gap-3 sm:grid-cols-2">{settings.editable.features.map(key=><label key={key} className="text-sm">{labels[key]??key}<select aria-label={labels[key]??key} value={features[key]===undefined||features[key]===null?'':String(features[key])} onChange={e=>setFeatures({...features,[key]:e.target.value})} className="mt-1 block w-full rounded-lg border p-2"><option value="">Follow plan ({settings.effective.inheritedFeatures[key]?'enabled':'disabled'})</option><option value="true">Enabled</option><option value="false">Disabled</option></select></label>)}</div></fieldset>
   <label className="block text-sm font-medium">Reason for change<input aria-label="Organization settings reason" required minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} disabled={busy} className="mt-1 block w-full rounded-lg border p-2"/></label>
   <button type="submit" disabled={busy||reason.trim().length<3} className="rounded-lg bg-[#117dff] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy?'Saving…':'Save organization settings'}</button>
   <p className="text-xs text-[#737373]">Effective plan: {settings.effective.plan}. Settings revision {settings.revision}.{settings.lastChange&&` Last changed ${new Date(settings.lastChange.at).toLocaleString()}: ${settings.lastChange.reason}`}</p>
  </form>}
 </section>;
}
