import React, { useState } from 'react';
import Seo from './Seo';
import './RuntimeProduct.css';
const steps = [
 ['Notice', 'A signal worth your attention.', 'A recurring customer question. An unfinished handoff. A result from your team. Runtime follows relevant signals from the connections you authorize.'],
 ['Connect', 'Context gives a signal meaning.', 'A signal becomes useful when it meets your company’s priorities. Runtime consults retained context, distinguishes evidence from assumptions, and asks when the direction is unclear.'],
 ['Coordinate', 'The right work. The right specialist.', 'Runtime turns a confirmed agenda into assignments for HyperAgents, with clear scope, timing and expected outcomes. You stay in control of permissions.'],
 ['Review', 'A result is only the beginning.', 'Runtime checks the deliverable, requests corrections when needed, and brings important results or decisions back to you.'],
 ['Carry forward', 'Tomorrow starts with what you learned.', 'Accepted results and useful lessons inform the next step. Scheduled follow-ups keep unfinished work connected instead of starting from another blank prompt.']
];
export default function RuntimeProduct() {
 const [active,setActive] = useState(0);
 return <main className="runtime-launch">
 <Seo pagePath="/runtime" canonical="https://runtime.singulancelabs.com/" />
 <nav className="rt-nav" aria-label="Runtime navigation"><a href="https://singulancelabs.com" className="rt-brand">SINGULANCE<span> / Runtime</span></a><div><a href="#intelligence">The idea</a><a href="https://singulancelabs.com/research/runtime">Research</a><a className="rt-nav-cta" href="https://next.singulancelabs.com/hivemind">Meet Runtime ↗</a></div></nav>
 <section className="rt-hero"><div className="rt-halo" aria-hidden="true"/><p className="rt-eyebrow">INTRODUCING RUNTIME · YOUR AI CHIEF OF STAFF</p><h1>Before you ask.<br/><span>Already connected.</span></h1><p className="rt-lead">Your company doesn’t move one prompt at a time.<br/>Its intelligence shouldn’t either.</p><a className="rt-link" href="#intelligence">Discover a different rhythm ↓</a><div className="rt-orbit" aria-hidden="true"><i/><i/><i/><div className="rt-character"><img src="/assets/runtime-computer-c2305f5b.webp" alt="" width="512" height="512"/></div><span className="rt-orbit-label rt-label-one">A signal appears.</span><span className="rt-orbit-label rt-label-two">A priority connects.</span><span className="rt-orbit-label rt-label-three">Work moves forward.</span></div><p className="rt-hero-foot">SIGNALS → CONTEXT → COORDINATION → REVIEW</p></section>
 <section id="intelligence" className="rt-statement"><p className="rt-eyebrow">FROM AGENDA TO MOMENTUM</p><h2>Less starting over.<br/><span>More moving forward.</span></h2><div className="rt-two"><p>You set the direction. Runtime connects what matters: your goals, your company’s context, and the work happening across your team.</p><p>It can notice relevant changes before your next request, surface a useful next step, and coordinate work within the authority you give it. When a decision belongs to you, it asks.</p></div></section>
 <section className="rt-timeline" aria-labelledby="rt-timeline-title"><header><p className="rt-eyebrow">INTELLIGENCE, IN MOTION</p><h2 id="rt-timeline-title">Not just an answer.<br/>A continuous thread.</h2><p>Follow the path from a signal to a reviewed result.</p></header><div className="rt-step-tabs" role="tablist" aria-label="Runtime work cycle">{steps.map((s,i)=><button key={s[0]} id={'rt-tab-'+i} role="tab" aria-selected={active===i} aria-controls="rt-step" onClick={()=>setActive(i)}><span>0{i+1}</span>{s[0]}</button>)}</div><div className="rt-step" id="rt-step" role="tabpanel" aria-labelledby={'rt-tab-'+active}><div className="rt-step-visual" aria-hidden="true"><div className="rt-lines"/><strong>0{active+1}</strong><span>{steps[active][0]}</span></div><div><p className="rt-eyebrow">THE RUNTIME CYCLE</p><h3>{steps[active][1]}</h3><p>{steps[active][2]}</p></div></div></section>
 <section className="rt-example"><p className="rt-eyebrow">AN ILLUSTRATIVE BUSINESS MOMENT</p><h2>One recurring question.<br/><span>A clearer next move.</span></h2><div className="rt-example-thread"><p><b>09:10 · Notice</b>A customer question keeps appearing in an authorized source.</p><p><b>09:12 · Connect</b>It relates to your confirmed goal: improve customer onboarding.</p><p><b>Next · Coordinate & review</b>A specialist investigates the gap. Runtime reviews the findings and brings you a proposed improvement.</p></div><small>Illustrative sequence, not a performance measurement. Sources, timing and available actions depend on your configuration and permissions.</small></section>
 <section className="rt-control"><p className="rt-eyebrow">YOUR COMPANY. YOUR DIRECTION.</p><h2>Proactive.<br/><span>With you in charge.</span></h2><div className="rt-principles"><article><span>01</span><h3>Selected signals.</h3><p>Connections you authorize. Context relevant to your goals.</p></article><article><span>02</span><h3>Visible uncertainty.</h3><p>Evidence stays distinct from hypotheses. Missing answers become questions.</p></article><article><span>03</span><h3>Human decisions.</h3><p>Approvals and consequential choices remain yours. Initiative doesn’t grant new authority.</p></article></div></section>
 <section className="rt-finale"><p className="rt-eyebrow">MEET YOUR COMPANY’S NEXT CHAPTER</p><h2>You shape the ambition.<br/><span>Runtime connects the work.</span></h2><a href="https://next.singulancelabs.com/hivemind" className="rt-button">Meet Runtime ↗</a><a href="https://singulancelabs.com/research/runtime" className="rt-read">Read the thinking behind Runtime →</a></section><footer className="rt-footer"><a href="https://singulancelabs.com">SINGULANCE</a><span>Intelligence with continuity.</span><a href="https://singulancelabs.com/privacy">Privacy</a></footer>
 </main>;
}
