import React from 'react';
import { ArrowRight, CheckCircle2, ClipboardCheck, Compass, Gauge, Lightbulb, Target, Users } from 'lucide-react';

const text = (value, fallback = '') => typeof value === 'string' || typeof value === 'number' ? String(value) : fallback;
const list = (value) => Array.isArray(value) ? value.filter((item) => typeof item === 'string' && item.trim()) : [];
const label = (value) => text(value, 'Unknown').replaceAll('_', ' ');

function SectionTitle({ icon: Icon, eyebrow, title }) {
  return <div className="flex items-start gap-2.5"><span className="grid h-8 w-8 shrink-0 place-items-center border border-[#c9d9f2] bg-white text-[#185bcc]"><Icon size={14} /></span><div><div className="text-[8px] font-mono uppercase tracking-wide text-[#6880a6]">{eyebrow}</div><h3 className="mt-0.5 text-[13px] font-semibold text-[#142b52]">{title}</h3></div></div>;
}

export default function GrowthPlanReport({ entry }) {
  const plan = entry?.plan;
  if (!plan) return null;
  const assessments = Array.isArray(plan.aspect_assessments) ? plan.aspect_assessments : [];
  const hypotheses = Array.isArray(plan.hypotheses) ? plan.hypotheses : [];
  const roadmap = Array.isArray(plan.roadmap) ? plan.roadmap : [];
  const stage = plan.stage || {};
  const delegation = plan.delegation || {};
  const measurement = stage.measurement || {};
  return <section className="mb-4 overflow-hidden border border-[#b8ccef] bg-white shadow-[0_16px_38px_-32px_rgba(17,63,142,0.6)]" aria-label="Growth Operating Plan">
    <div className="bg-[#173d86] px-5 py-5 text-white sm:px-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[8px] font-mono uppercase tracking-[0.16em] text-[#bfd2ff]">HQ decision · Growth Operating Plan</div><h2 className="mt-2 text-[20px] font-semibold">{text(plan.goal?.title, 'Company growth plan')}</h2><p className="mt-2 max-w-4xl text-[11px] leading-5 text-[#dce7ff]">{text(plan.executive_thesis, 'The current baseline has been converted into a bounded operating stage.')}</p></div><span className="inline-flex items-center gap-1.5 border border-[#8eade8] bg-[#214b99] px-2.5 py-1 text-[8px] font-mono uppercase"><CheckCircle2 size={10} />Plan filed</span></div><div className="mt-4 flex flex-wrap gap-x-5 gap-y-1 text-[8px] font-mono uppercase text-[#bfd2ff]"><span>Baseline {text(plan.baseline_ref?.resource_id, '').slice(0, 8)}</span><span>{entry?.captured_at ? new Date(entry.captured_at).toLocaleString() : 'Saved plan'}</span><span>{label(entry?.mode)}</span></div></div>

    <div className="grid border-b border-[#d8e2f3] lg:grid-cols-[1.05fr_0.95fr]"><div className="border-b border-[#d8e2f3] p-5 lg:border-b-0 lg:border-r"><SectionTitle icon={Target} eyebrow="Selected constraint" title={label(plan.constraint?.type)} /><p className="mt-3 text-[11px] leading-5 text-[#334b70]">{text(plan.constraint?.statement, 'No operating constraint recorded.')}</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><div><div className="text-[8px] font-mono uppercase text-[#6880a6]">Known facts</div>{list(plan.constraint?.known_facts).map((item) => <p key={item} className="mt-1.5 text-[9.5px] leading-4 text-[#425b80]">• {item}</p>)}</div><div><div className="text-[8px] font-mono uppercase text-[#6880a6]">Unknowns to resolve</div>{list(plan.constraint?.unknowns).map((item) => <p key={item} className="mt-1.5 text-[9.5px] leading-4 text-[#425b80]">• {item}</p>)}</div></div></div>
      <div className="bg-[#f5f8fd] p-5"><SectionTitle icon={Compass} eyebrow="Current stage" title={text(stage.name, 'Next operating stage')} /><p className="mt-3 text-[11px] leading-5 text-[#334b70]">{text(stage.objective)}</p><div className="mt-4 grid grid-cols-2 gap-px overflow-hidden border border-[#cedbef] bg-[#cedbef]"><div className="bg-white p-2.5"><div className="text-[14px] font-semibold text-[#173d86]">{text(stage.duration_days, '—')}</div><div className="text-[7px] font-mono uppercase text-[#6880a6]">Days</div></div><div className="bg-white p-2.5"><div className="text-[14px] font-semibold text-[#173d86]">Day {text(stage.checkpoint_day, '—')}</div><div className="text-[7px] font-mono uppercase text-[#6880a6]">Checkpoint</div></div></div></div></div>

    <div className="border-b border-[#d8e2f3] p-5"><SectionTitle icon={Gauge} eyebrow="Company assessment" title="What the baseline says across the operating system" /><div className="mt-4 grid gap-px overflow-hidden border border-[#d8e2f3] bg-[#d8e2f3] sm:grid-cols-2 xl:grid-cols-3">{assessments.map((item) => <div key={text(item.aspect)} className="bg-white p-3"><div className="flex items-center justify-between gap-2"><span className="text-[9px] font-semibold capitalize text-[#17345f]">{label(item.aspect)}</span><span className={`text-[7px] font-mono uppercase ${item.status === 'constraint' ? 'text-[#b13d4d]' : item.status === 'strength' ? 'text-[#197054]' : 'text-[#7a6b55]'}`}>{label(item.status)}</span></div><p className="mt-2 text-[9.5px] leading-4 text-[#526b91]">{text(item.implication, list(item.observations)[0] || 'Awaiting stronger evidence.')}</p><div className="mt-2 border-t border-[#edf1f7] pt-2 text-[8.5px] leading-4 text-[#185bcc]">Next: {text(item.next_move, 'Observe and reassess.')}</div></div>)}</div></div>

    <div className="grid border-b border-[#d8e2f3] lg:grid-cols-2"><div className="border-b border-[#d8e2f3] p-5 lg:border-b-0 lg:border-r"><SectionTitle icon={Lightbulb} eyebrow="Growth hypotheses" title="What HQ expects to learn" /><div className="mt-4 space-y-3">{hypotheses.map((item, index) => <div key={`${index}-${text(item.statement)}`} className="border-l-2 border-[#7ea5eb] pl-3"><div className="flex items-center gap-2"><span className="text-[8px] font-mono text-[#185bcc]">0{index + 1}</span><span className="text-[7px] font-mono uppercase text-[#6880a6]">{text(item.confidence, 'LOW')} confidence</span></div><p className="mt-1 text-[10px] font-medium leading-4 text-[#273f65]">{text(item.statement)}</p><p className="mt-1 text-[8.5px] leading-4 text-[#60789e]">Signal: {text(item.expected_signal, 'Not defined')}</p></div>)}</div></div>
      <div className="p-5"><SectionTitle icon={Gauge} eyebrow="Measurement contract" title={text(measurement.primary_signal, 'Primary signal')} /><dl className="mt-4 space-y-2 text-[9.5px]"><div><dt className="font-mono text-[7px] uppercase text-[#6880a6]">Source</dt><dd className="mt-1 text-[#334b70]">{text(measurement.source, 'Not connected')}</dd></div><div><dt className="font-mono text-[7px] uppercase text-[#6880a6]">Decision rule</dt><dd className="mt-1 leading-4 text-[#334b70]">{text(measurement.decision_rule, 'Review at checkpoint.')}</dd></div><div><dt className="font-mono text-[7px] uppercase text-[#6880a6]">Stop condition</dt><dd className="mt-1 leading-4 text-[#334b70]">{text(measurement.stop_condition, 'No stop condition recorded.')}</dd></div></dl></div></div>

    <div className="grid lg:grid-cols-[1fr_0.8fr]"><div className="border-b border-[#d8e2f3] p-5 lg:border-b-0 lg:border-r"><SectionTitle icon={Users} eyebrow="Delegated work order" title={label(delegation.room_tag)} /><p className="mt-3 text-[11px] font-medium leading-5 text-[#273f65]">{text(delegation.objective)}</p><p className="mt-2 text-[9.5px] leading-4 text-[#526b91]">Deliverable: {text(delegation.deliverable)}</p><div className="mt-3 space-y-1.5">{list(delegation.acceptance_criteria).map((item) => <div key={item} className="flex gap-2 text-[9px] leading-4 text-[#425b80]"><ClipboardCheck size={11} className="mt-0.5 shrink-0 text-[#185bcc]" />{item}</div>)}</div></div>
      <div className="bg-[#f7f9fc] p-5"><SectionTitle icon={ArrowRight} eyebrow="Directional roadmap" title="What follows this stage" /><div className="mt-4 space-y-3">{roadmap.map((item, index) => <div key={`${index}-${text(item.horizon)}`}><div className="text-[8px] font-mono uppercase text-[#185bcc]">{label(item.horizon)}</div><div className="mt-1 text-[10px] font-medium text-[#273f65]">{label(item.focus)}</div><p className="mt-1 text-[8.5px] leading-4 text-[#60789e]">Activate when: {text(item.activation_condition, 'The current stage supplies enough evidence.')}</p></div>)}</div></div></div>
  </section>;
}
