export const SITE = 'https://singulancelabs.com';
export const OG_IMAGE = `${SITE}/og-cover-seo.jpg`;
export const PUBLIC_PAGES = {
  '/': { title: 'SINGULANCE | AI Workforce, Memory and Voice Agents', heading: 'SINGULANCE — AI workforce that runs inside memory', description: 'Discover HIVEMIND organizational memory, HyperAgents digital teammates and TARA voice agents. Explore SINGULANCE research and AI workforce tools.', summary: 'SINGULANCE brings organizational memory, digital teammates and voice agents together. HIVEMIND connects company knowledge; HyperAgents work with that context; TARA supports voice conversations.' },
  '/hivemind': { title: 'HIVEMIND: Your Company Brain | SINGULANCE', heading: 'HIVEMIND — your company brain', description: 'Explore HIVEMIND company memory, connected apps, evidence-backed answers and persistent AI teammates.', summary: 'HIVEMIND brings your company knowledge, AI teammates and voice conversations into one authenticated workspace.' },
  '/tara': { title: 'TARA Voice | SINGULANCE', heading: 'TARA — voice with company context', description: 'Explore TARA, the voice experience in the HIVEMIND workspace.', summary: 'TARA brings voice conversations into HIVEMIND. Sign in and choose Voice to open Tara.' },
  '/hyperagents': { title: 'HyperAgents: AI Teammates | SINGULANCE', heading: 'HyperAgents — your AI teammates', description: 'Explore persistent AI teammate rooms, task results, artifacts and Runtime coordination in HIVEMIND.', summary: 'HyperAgents keep each teammate’s conversation, work and deliverables in a persistent room.' },
  '/account-deletion': {title:'Delete your SINGULANCE account',heading:'Delete your account',description:'Request deletion of your SINGULANCE account from your profile or contact the privacy team if you cannot sign in.',summary:'Account deletion is available in your profile on the app and web. Shared records, external copies and legally retained records may remain; source cleanup can be pending.'},
  '/runtime': { title: 'Runtime — Before you ask. Already connected. | SINGULANCE', heading: 'Runtime', description: 'Meet Runtime, your AI Chief of Staff. Connect authorized company signals, confirmed goals and reviewed team work in one continuous thread.', summary: 'Runtime connects relevant signals to company priorities, coordinates HyperAgents, reviews results and carries useful context forward, within your permissions.' },
  '/research/runtime': { title: 'Runtime: intelligence with continuity | SINGULANCE Research', heading: 'Runtime: intelligence with continuity', description: 'The design principles behind Runtime: relevant signals, confirmed goals, specialist coordination, review and human control.', summary: 'A product research design note on proactive company intelligence, its boundaries and proposed evaluation dimensions.' },
  '/research': { title: 'AI Memory and Agent Research | SINGULANCE', heading: 'SINGULANCE Research', description: 'Explore SINGULANCE research on agent memory, cognitive swarm intelligence and post-quantum cryptography, with published methods and benchmarks.', summary: 'Read research on persistent agent memory, cognitive swarm intelligence and post-quantum cryptography. Explore the papers and their supporting methods.' },
  '/research/icarus': { title: 'ICARUS: Agent Memory Filesystem | SINGULANCE Research', heading: 'ICARUS — an agent memory filesystem', description: 'Explore ICARUS, SINGULANCE’s agent memory filesystem combining vector, entity, temporal and graph retrieval in one file. Read the research and methods.', summary: 'ICARUS explores a single-file agent memory architecture combining vector, entity, temporal and graph retrieval. The research page describes the design and evaluation.' },
  '/research/cognitive-swarm-intelligence': { title: 'Cognitive Swarm Intelligence | SINGULANCE Research', heading: 'Cognitive Swarm Intelligence', description: 'Read SINGULANCE research on cognitive swarm intelligence: shared organizational memory, coordinated agents and the architecture behind HIVEMIND.', summary: 'Explore the architecture of agents working with shared organizational memory, and the relationships between knowledge, retrieval and coordinated work.' },
  '/research/post-quantum-cryptography': { title: 'Post-Quantum Cryptography | SINGULANCE Research', heading: 'Post-Quantum Cryptography', description: 'Explore SINGULANCE’s research on hybrid post-quantum transport, signed memory writes and tamper-evident audit chains for organizational AI systems.', summary: 'Read the research on hybrid post-quantum transport, memory-write signatures and tamper-evident audit chains, including the underlying standards and implementation.' },
  '/benchmark': { title: 'HIVEMIND Memory Benchmarks | SINGULANCE', heading: 'HIVEMIND Memory Benchmarks', description: 'Review HIVEMIND memory retrieval benchmarks, evaluation methods and published results. Explore the evidence behind SINGULANCE’s memory research.', summary: 'Review the published memory retrieval evaluation, its methods and results. Benchmark claims should be read alongside their evaluation conditions.' },
  '/privacy': { title: 'Privacy Policy | SINGULANCE', heading: 'Privacy Policy', description: 'Read SINGULANCE’s privacy policy, including information about personal data, connected services, data protection and your privacy rights.', summary: 'Read how SINGULANCE handles personal data and connected services, and learn about your privacy rights. The full policy is available on this page.' },
  '/security': { title: 'Security | SINGULANCE', heading: 'Security', description: 'Learn about SINGULANCE security practices and data protection for organizational memory and AI agents. Review the published security information.', summary: 'Review SINGULANCE’s published security information for organizational memory and AI agents.' },
  '/cookies': { title: 'Cookie Policy | SINGULANCE', heading: 'Cookie Policy', description: 'Read SINGULANCE’s cookie policy and learn about essential storage, optional analytics and how to manage your privacy and cookie preferences.', summary: 'Learn about essential storage and optional analytics. Manage your consent through the privacy choices available on the website.' },
};
export const canonicalFor = (path) => path === '/runtime' ? 'https://runtime.singulancelabs.com/' : `${SITE}${path}`;
export const schemaFor = (path) => ({
  '@context': 'https://schema.org',
  '@graph': [
    { '@type': 'Organization', '@id': `${SITE}/#organization`, name: 'SINGULANCE', url: `${SITE}/`, logo: `${SITE}/singulance-mark-192.png` },
    { '@type': 'WebSite', '@id': `${SITE}/#website`, name: 'SINGULANCE', url: `${SITE}/`, publisher: { '@id': `${SITE}/#organization` } },
    { '@type': 'WebPage', '@id': canonicalFor(path), url: canonicalFor(path), name: PUBLIC_PAGES[path].title, description: PUBLIC_PAGES[path].description, isPartOf: { '@id': `${SITE}/#website` }, inLanguage: 'en' },
    ...(path === '/' ? [] : [{ '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'SINGULANCE', item: `${SITE}/` }, { '@type': 'ListItem', position: 2, name: PUBLIC_PAGES[path].heading, item: canonicalFor(path) }] }]),
  ],
});
