import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, CalendarDays, CheckCircle2, Loader2, Pause, Play, RefreshCw, RotateCcw, Rocket, UsersRound, X } from 'lucide-react';
import ActionCard from './ActionCard';
import ChannelTab from './ChannelTab';
import CampaignRoomExperience from './CampaignRoomExperience';
import { CampaignReport } from '../rooms/reports';

const LABEL = { x_organic: 'X', gmail: 'Email', tara: 'TARA' };
const EVENT_LABEL = {
  campaign_created: 'Campaign and dedicated Room created',
  campaign_generation_started: 'Agents started gathering and debating',
  campaign_plan_ready: 'Campaign plan contract accepted',
  campaign_ready: 'Campaign is ready for your approval',
  campaign_needs_input: 'Plan contract needs more input',
  campaign_generation_needs_input: 'Campaign Room needs more input',
  campaign_generation_failed: 'Campaign Room generation failed',
  campaign_approved: 'Campaign launched and scheduled',
  campaign_action_approved: 'Campaign action approved',
  campaign_action_succeeded: 'Campaign action completed',
  campaign_action_failed: 'Campaign action needs attention',
  campaign_action_retry_requested: 'Action retry approved by user',
  campaign_action_reconciled: 'Provider action reconciled',
  campaign_action_reconciliation_pending: 'Provider inspection still required',
  campaign_action_edited: 'Action edited and new plan version created',
  campaign_action_removed: 'Action removed and new plan version created',
  campaign_regeneration_started: 'Campaign Room regeneration started',
  campaign_metrics_synced: 'Campaign performance synchronized',
  campaign_paused: 'Campaign paused',
  campaign_resumed: 'Campaign resumed',
  campaign_completed: 'Campaign completed',
};

export default function CampaignDetail({ campaign, loading, onBack, onControl, onApproveAction, onRetryAction, onReconcileAction, onEditAction, onRemoveAction, onRegenerate, busy, executionEnabled = false }) {
  const [tab, setTab] = useState(() => campaign?.status === 'GENERATING' ? 'room' : 'overview');
  const [launchOpen, setLaunchOpen] = useState(false);
  const previousStatus = useRef(campaign?.status);
  const [regenerateOpen, setRegenerateOpen] = useState(false); const [feedback, setFeedback] = useState('');
  const actions = campaign?.actions || []; const plan = campaign?.planVersions?.[0];
  const events = campaign?.events || [];
  const channelMetrics = Object.fromEntries((campaign?.channels || []).map((channel) => [channel.channel, channel.metrics || {}]));
  const tabs = useMemo(() => ['overview', 'strategy', 'audience', ...campaign.requestedChannels, 'schedule', 'performance', 'room', 'audit'], [campaign.requestedChannels]);
  useEffect(() => {
    if (previousStatus.current === 'GENERATING' && campaign?.status === 'READY_FOR_APPROVAL') setTab('overview');
    previousStatus.current = campaign?.status;
  }, [campaign?.status]);
  if (loading && !campaign) return <div className="h-full grid place-items-center"><Loader2 className="animate-spin text-[#77716a]" size={22} /></div>;
  return <div className="h-full overflow-y-auto bg-[#fbfaf6]">
    <div className="sticky top-0 z-10 bg-[#fbfaf6]/95 backdrop-blur border-b border-[#dfdbd4]">
      <div className="px-4 sm:px-7 pt-4"><button onClick={onBack} className="inline-flex items-center gap-1.5 text-[11px] font-semibold text-[#6f6962]"><ArrowLeft size={13} />All campaigns</button>
        <div className="mt-3 flex flex-col sm:flex-row sm:items-end gap-3 justify-between"><div><div className="flex items-center gap-2"><h1 className="text-[20px] font-semibold text-[#171717]">{campaign.name}</h1><span className="text-[9px] font-mono uppercase bg-[#efede8] rounded px-1.5 py-0.5">{campaign.status}</span></div><p className="text-[11.5px] text-[#746e67] mt-1 max-w-3xl">{campaign.goal}</p></div>
          <div className="flex gap-2">{['READY_FOR_APPROVAL', 'NEEDS_INPUT', 'FAILED'].includes(campaign.status) ? <button onClick={() => setRegenerateOpen(true)} disabled={busy} className="h-9 px-3 border border-[#bdb7af] rounded-md text-[11.5px] font-semibold inline-flex items-center gap-1.5"><RotateCcw size={13} />Regenerate</button> : null}{campaign.status === 'READY_FOR_APPROVAL' ? <button onClick={() => setLaunchOpen(true)} disabled={busy || !executionEnabled} title={executionEnabled ? 'Review the launch schedule' : 'Execution is disabled during the generate-only pilot'} className="h-9 px-4 bg-[#171717] text-white rounded-md text-[11.5px] font-semibold inline-flex items-center gap-1.5 disabled:bg-[#aaa49c]"><Rocket size={13} />Launch campaign</button> : null}{['RUNNING', 'SCHEDULED'].includes(campaign.status) ? <button onClick={() => onControl('pause')} disabled={busy} className="h-9 px-3 border border-[#bdb7af] rounded-md text-[11.5px] font-semibold inline-flex items-center gap-1.5"><Pause size={13} />Pause</button> : null}{campaign.status === 'PAUSED' ? <button onClick={() => onControl('resume')} disabled={busy || !executionEnabled} className="h-9 px-3 border border-[#bdb7af] rounded-md text-[11.5px] font-semibold inline-flex items-center gap-1.5 disabled:opacity-40"><Play size={13} />Resume</button> : null}</div>
        </div>
      </div>
      <div className="mt-4 px-4 sm:px-7 flex gap-5 overflow-x-auto">{tabs.map((id) => <button key={id} onClick={() => setTab(id)} className={`h-9 shrink-0 text-[10.5px] font-semibold capitalize border-b-2 ${tab === id ? 'border-[#171717] text-[#171717]' : 'border-transparent text-[#817b74]'}`}>{LABEL[id] || (id === 'room' ? 'Campaign Room' : id)}</button>)}</div>
    </div>
    <main className="px-4 sm:px-7 py-6 max-w-6xl">
      {regenerateOpen ? <div className="mb-5 border-y border-[#d8d3cc] py-4"><div className="flex items-center justify-between"><div><div className="text-[12px] font-semibold">Regenerate in the same Campaign Room</div><div className="text-[10.5px] text-[#77716a] mt-0.5">The agents keep this campaign identity and create a new immutable plan version.</div></div><button onClick={() => setRegenerateOpen(false)} className="w-8 h-8 grid place-items-center" title="Close"><X size={14} /></button></div><textarea rows={3} value={feedback} onChange={(event) => setFeedback(event.target.value)} placeholder="What should the agents change or improve?" className="mt-3 w-full border border-[#cfc9c1] rounded-md p-3 text-[11.5px] resize-none" /><button onClick={async () => { try { await onRegenerate(feedback); setRegenerateOpen(false); setFeedback(''); } catch { /* parent surfaces the API error */ } }} disabled={busy} className="mt-2 h-8 px-3 bg-[#171717] text-white rounded-md text-[10.5px] font-semibold inline-flex items-center gap-1.5"><RotateCcw size={12} />Start regeneration</button></div> : null}
      {launchOpen ? <section className="mb-5 rounded-md border border-[#bdb7af] bg-white p-4" aria-label="Launch confirmation"><div className="flex items-start justify-between gap-4"><div><h3 className="text-[13px] font-semibold">Launch this campaign?</h3><p className="mt-1 text-[10.5px] text-[#77716a]">The first action becomes due now. Every remaining action is scheduled from this approval time.</p></div><button onClick={() => setLaunchOpen(false)} className="grid h-8 w-8 place-items-center" title="Close launch confirmation"><X size={14} /></button></div><div className="mt-4 grid gap-px border border-[#dfdbd4] bg-[#dfdbd4] sm:grid-cols-3"><div className="bg-[#fbfaf6] p-3"><div className="flex items-center gap-1.5 text-[9px] font-mono uppercase text-[#817b74]"><Rocket size={11} />Channels</div><div className="mt-1 text-[11px] font-semibold">{campaign.requestedChannels.map((id) => LABEL[id] || id).join(', ')}</div></div><div className="bg-[#fbfaf6] p-3"><div className="flex items-center gap-1.5 text-[9px] font-mono uppercase text-[#817b74]"><UsersRound size={11} />Audience</div><div className="mt-1 text-[11px] font-semibold">{campaign.audience?.length || 0} selected contacts</div></div><div className="bg-[#fbfaf6] p-3"><div className="flex items-center gap-1.5 text-[9px] font-mono uppercase text-[#817b74]"><CalendarDays size={11} />Schedule</div><div className="mt-1 text-[11px] font-semibold">{actions.length} action{actions.length === 1 ? '' : 's'} from launch time</div></div></div><div className="mt-4 flex justify-end gap-2"><button onClick={() => setLaunchOpen(false)} className="h-9 rounded-md border border-[#bdb7af] px-3 text-[11px] font-semibold">Keep reviewing</button><button onClick={async () => { if (await onControl('launch')) setLaunchOpen(false); }} disabled={busy} className="inline-flex h-9 items-center gap-1.5 rounded-md bg-[#171717] px-4 text-[11px] font-semibold text-white disabled:bg-[#aaa49c]"><Rocket size={13} />Confirm launch</button></div></section> : null}
      {!executionEnabled ? <div className="mb-4 border border-[#d8d3cc] bg-white rounded-md px-4 py-3 text-[11px] text-[#615c56]"><strong>Generate-only pilot:</strong> plans and ready actions are available, while external publishing is intentionally disabled.</div> : null}
      {campaign.status === 'GENERATING' ? <div className="border border-[#d8d3cc] rounded-md p-5 bg-white flex gap-3"><Loader2 size={16} className="animate-spin mt-0.5 shrink-0" /><div><div className="text-[12.5px] font-semibold">Campaign Room is working</div><div className="text-[11px] text-[#77716a] mt-1">Agents are gathering evidence, debating the strategy, and compiling ready actions. This continues if you leave the page.</div>{events[0] ? <div className="text-[9.5px] font-mono uppercase text-[#817b74] mt-2">{EVENT_LABEL[events[0].eventType] || events[0].eventType.replaceAll('_', ' ')}</div> : null}</div></div> : null}
      {campaign.status === 'NEEDS_INPUT' ? <div className="border border-amber-300 bg-amber-50 rounded-md p-4 text-[11.5px] text-amber-900"><strong>Plan needs input.</strong> {campaign.lastError}</div> : null}
      {tab === 'overview' ? <div><div className="grid sm:grid-cols-4 border-y border-[#dfdbd4] divide-y sm:divide-y-0 sm:divide-x divide-[#dfdbd4]">{[['Actions', actions.length], ['Ready or queued', actions.filter((x) => ['READY', 'QUEUED', 'AWAITING_APPROVAL'].includes(x.status)).length], ['Completed', actions.filter((x) => x.status === 'SUCCEEDED').length], ['Channels', campaign.requestedChannels.length]].map(([label, value]) => <div key={label} className="py-4 sm:px-4 first:pl-0"><div className="text-[20px] font-semibold">{value}</div><div className="text-[9.5px] font-mono uppercase text-[#817b74] mt-1">{label}</div></div>)}</div>{plan ? <div className="mt-6"><CampaignReport report={{ bundle: plan.bundle, content: plan.reportMarkdown }} taskTitle={campaign.name} /></div> : <div className="py-10 text-[11.5px] text-[#817b74]">The operating report appears when the Campaign Room completes.</div>}</div> : null}
      {tab === 'strategy' ? <CampaignReport report={plan ? { bundle: plan.bundle, content: plan.reportMarkdown } : null} taskTitle={campaign.name} /> : null}
      {tab === 'audience' ? <div className="text-[12px] text-[#615c56]">{plan?.bundle?.audience?.rationale || 'Audience selection is still being generated.'}</div> : null}
      {campaign.requestedChannels.includes(tab) ? <ChannelTab channel={tab} actions={actions} onApprove={onApproveAction} onRetry={onRetryAction} onReconcile={onReconcileAction} onEdit={onEditAction} onRemove={onRemoveAction} busy={busy} /> : null}
      {tab === 'schedule' ? <div>{[...actions].sort((a, b) => new Date(a.scheduledAt || 0) - new Date(b.scheduledAt || 0)).map((action) => <ActionCard key={action.id} action={action} />)}</div> : null}
      {tab === 'performance' ? <div><div className="flex items-center justify-between border-b border-[#d8d3cc] pb-3"><div><h3 className="text-[12.5px] font-semibold">Measured performance</h3><p className="text-[10.5px] text-[#817b74] mt-0.5">Provider and outcome-ledger totals. Follower changes are observational, not causal attribution.</p></div><button onClick={() => onControl('sync')} disabled={busy || !actions.some((action) => action.status === 'SUCCEEDED')} className="h-8 px-3 border border-[#bdb7af] rounded-md text-[10.5px] font-semibold inline-flex items-center gap-1.5 disabled:opacity-40"><RefreshCw size={12} />Refresh</button></div>{campaign.requestedChannels.map((channel) => { const metrics = channelMetrics[channel] || {}; const rows = channel === 'x_organic' ? [['Impressions', metrics.impressions], ['Engagements', metrics.engagements], ['Link clicks', metrics.url_clicks], ['Followers', metrics.followers], ['Follower change', metrics.follower_delta], ['Engagement rate', typeof metrics.engagement_rate === 'number' ? `${(metrics.engagement_rate * 100).toFixed(2)}%` : null]] : channel === 'gmail' ? [['Sent', metrics.sent], ['Replies', metrics.replied], ['Booked', metrics.booked], ['Bounced', metrics.bounced]] : [['Calls', metrics.calls], ['Completed', metrics.completed], ['Booked', metrics.booked], ['No answer', metrics.no_answer], ['Blocked', metrics.blocked]]; return <section key={channel} className="py-5 border-b border-[#dfdbd4]"><div className="text-[10px] font-mono uppercase text-[#77716a]">{LABEL[channel] || channel}</div><div className="mt-3 grid grid-cols-2 sm:grid-cols-3 gap-px bg-[#dfdbd4] border border-[#dfdbd4]">{rows.map(([label, value]) => <div key={label} className="bg-[#fbfaf6] p-3 min-h-16"><div className="text-[18px] font-semibold">{value ?? 0}</div><div className="text-[9.5px] text-[#817b74] mt-1">{label}</div></div>)}</div>{metrics.synced_at ? <div className="mt-2 text-[9.5px] text-[#8a847d]">Last synchronized {new Date(metrics.synced_at).toLocaleString()}</div> : <div className="mt-2 text-[9.5px] text-[#8a847d]">Metrics appear after the first successful action and refresh.</div>}</section>})}</div> : null}
      {tab === 'room' ? <CampaignRoomExperience campaign={campaign} ReportComponent={CampaignReport} /> : null}
      {tab === 'audit' ? <div className="space-y-0">{events.length ? events.map((event) => <div key={event.id} className="grid grid-cols-[18px_1fr] gap-2 py-3 border-b border-[#e1ddd6]"><CheckCircle2 size={12} className="text-[#6f6962] mt-0.5" /><div><div className="text-[11px] font-semibold">{EVENT_LABEL[event.eventType] || event.eventType.replaceAll('_', ' ')}</div><div className="text-[9.5px] text-[#817b74] mt-0.5">{new Date(event.createdAt).toLocaleString()}</div></div></div>) : <div className="text-[11px] text-[#817b74]">Pipeline events appear here as the campaign progresses.</div>}</div> : null}
    </main>
  </div>;
}
