export const mobileCopy = {
  en: {
    nav: {
      links: {
        solutions: 'Solutions',
        research: 'Research',
        contact: 'Contact',
      },
      lightMode: 'Light Mode',
      darkMode: 'Dark Mode',
      languageLabel: 'Language',
    },
    hero: {
      series: 'DV — Series',
      year: '/2026',
      metaCode: 'DV-S001',
      coordinates: '52.3759° N, 9.7320° E',
      headline: ['AI-POWERED', 'ENTERPRISE', 'AUTOMATION'],
      primaryCta: 'HIVEMIND',
      secondaryCta: 'TARA_Enterprise',
      taglineLead: 'Not what looks cool — ',
      taglineStrong: 'what actually lasts.',
      imageLocation: 'Hannover, Germany',
      footerLeft: "Made by Da'Vinci Solutions",
      footerRight: 'Save for this later',
    },
    tara: {
      sectionLabel: 'Solutions / 01',
      titlePrefix: 'Meet',
      titleAccent: 'TARA',
      subtitle: 'The soul of your brand. Available 24/7.',
      posterStatus: 'Idle',
      posterReady: 'Ready to start',
      posterEyebrow: 'DAVINCI AI',
      posterTitle: 'DAVINCI AI x TARA',
      posterLocale: 'DE',
      posterButton: 'Start call',
      posterHint: 'Click the poster to start the voice call',
      conversation: [
        { from: 'user', label: 'YOU', text: 'What does Da Vinci AI do?' },
        { from: 'tara', label: 'TARA', text: 'We build enterprise AI infrastructure across voice, memory, and sovereign deployment.' },
        { from: 'user', label: 'YOU', text: 'And TARA handles the voice side?' },
        { from: 'tara', label: 'TARA', text: 'Yes. Calls, lead qualification, appointment booking, and support in real time.' },
        { from: 'user', label: 'YOU', text: 'Is it GDPR compliant?' },
        { from: 'tara', label: 'TARA', text: 'Fully EU-hosted. No transatlantic data transfer.' },
      ],
      avgResponse: 'AVG RESPONSE: 480ms',
      reasoningTitle: 'Not a chatbot. Not a script.',
      reasoningBody: 'TARA is the first enterprise voice agent that reasons — not retrieves. While your customer is still speaking, TARA processes four layers in parallel:',
      reasoningPoints: [
        'What the user said',
        'What they actually mean',
        'The root problem underneath',
        'The optimal path forward',
      ],
      reasoningFooter: 'Response delivered in under 500ms. Indistinguishable from human.',
      variantsLabel: 'Four variants. One intelligence.',
      variants: [
        { num: '01', title: 'Visual Co-Pilot', desc: "Sees the user's screen. Guides them through any form, dashboard, or process in real time." },
        { num: '02', title: 'Telephony', desc: 'Replaces IVR completely. Speaks German natively. Books appointments, resolves tickets, qualifies leads.' },
        { num: '03', title: 'Web Call', desc: 'Your website speaks. Visitors talk to TARA directly from the browser. Zero telco costs.' },
        { num: '04', title: 'Chat Assistant', desc: 'Onboards. Answers. Escalates. Always available. Never forgets.' },
      ],
    },
    hivemind: {
      sectionLabel: 'Solutions / 02',
      topLabel: 'Memory Engine',
      metaCode: 'DV-HM002',
      metaSuffix: 'Second Brain',
      headlineAccent: 'HIVEMIND',
      headlineLines: ['Your Sovereign', 'Memory Engine'],
      subtitle: 'Your second brain that never forgets. Connect your emails, notes, and conversations — then retrieve the exact answer months later.',
      primaryCta: 'Try Free',
      secondaryCta: '87.2% Accuracy',
      stats: [
        { val: '<250ms', label: 'Recall' },
        { val: '87.2%', label: 'LongMemEval Benchmark' },
        { val: '13+', label: 'MCP Tools' },
      ],
      graphLabel: 'Interactive · hover to explore',
      featuresLabel: 'How it works',
      features: [
        { n: '01', title: 'It remembers everything', desc: 'Every conversation, email, and document — stored, indexed, and connected.', tag: 'Total recall' },
        { n: '02', title: 'It connects the dots', desc: 'Related ideas from Slack, Gmail, and your docs are linked automatically.', tag: 'Knowledge graph' },
        { n: '03', title: 'It gets smarter over time', desc: 'Three AI agents scan for duplicates, conflicts, and missing links.', tag: 'Self-improving' },
        { n: '04', title: 'Your data stays yours', desc: 'Hosted in Frankfurt. GDPR by architecture. Zero US data transfers.', tag: 'EU sovereign' },
      ],
      useCasesLabel: 'Built for',
      useCasesTitle: 'Anyone who thinks for a living',
      useCases: [
        { e: '💼', t: 'Founders', d: 'Never lose a meeting insight or investor feedback.' },
        { e: '🧑‍💻', t: 'Developers', d: 'Codebase context and decisions — always retrievable.' },
        { e: '📝', t: 'Researchers', d: 'Connect papers, notes, and conversations.' },
        { e: '🏢', t: 'Teams', d: 'Shared memory. When someone leaves, knowledge stays.' },
      ],
      footerLeft: 'HIVEMIND Memory Engine',
      footerRight: 'EU Sovereign · GDPR Native',
    },
    enterprise: {
      sectionLabel: 'Solutions / 03',
      title: ['Enterprise', 'Deployment'],
      subtitle: "Deploy sovereign AI infrastructure on your terms. Full control over data residency, compliance, and operational policies with Da Vinci's managed platform.",
      features: [
        { title: 'Sovereign Hosting', desc: 'EU data centers, GDPR compliant by design' },
        { title: 'Custom Integration', desc: 'Connect to your existing tools and workflows' },
        { title: 'Managed Platform', desc: 'We handle infrastructure, you handle innovation' },
      ],
      compliance: ['SOC 2 Compliant', 'EU Data Residency', 'End-to-End Encryption'],
    },
    brand: {
      background: ['BRAND', 'VOICE'],
      tagline: 'Your digital presence, amplified.',
      title: 'Meet TARA.',
      description: "Your brand's first employee. She engages, qualifies, and converts — in your voice, across web, calls, and video.",
      cta: 'Start Conversation',
      footer: ['WEB', 'VOICE', 'VIDEO'],
    },
    research: {
      label: 'Research',
      title: ['Cognitive Swarm', 'Intelligence'],
      quote: '"The system remembers. The agents just act."',
      citation: '— DavinciAI Labs, CSI Paper 2026',
      body: 'We published the architecture behind HIVEMIND. CSI proposes environment-centric intelligence — where memory, behavior, and policy are externalized into a shared cognitive substrate.',
      cta: 'Read the paper',
    },
    about: {
      label: 'Contact',
      title: 'Get in touch',
      body: "Have a question, partnership inquiry, or just want to say hello? We'd love to hear from you.",
      email: 'Email',
      locationLabel: 'Location',
      location: 'Hannover, Germany',
      cta: 'Send us a message',
      footer: "Da'Vinci Solutions / 2026",
    },
  },
  de: {
    nav: {
      links: {
        solutions: 'Lösungen',
        research: 'Forschung',
        contact: 'Kontakt',
      },
      lightMode: 'Hellmodus',
      darkMode: 'Dunkelmodus',
      languageLabel: 'Sprache',
    },
    hero: {
      series: 'DV — Serie',
      year: '/2026',
      metaCode: 'DV-S001',
      coordinates: '52.3759° N, 9.7320° E',
      headline: ['KI-GETRIEBENE', 'UNTERNEHMENS-', 'AUTOMATION'],
      primaryCta: 'HIVEMIND',
      secondaryCta: 'TARA_Enterprise',
      taglineLead: 'Nicht das, was cool aussieht — ',
      taglineStrong: 'sondern das, was wirklich bleibt.',
      imageLocation: 'Hannover, Deutschland',
      footerLeft: "Gemacht von Da'Vinci Solutions",
      footerRight: 'Für später speichern',
    },
    tara: {
      sectionLabel: 'Lösungen / 01',
      titlePrefix: 'Triff',
      titleAccent: 'TARA',
      subtitle: 'Die Seele Ihrer Marke. Rund um die Uhr verfügbar.',
      posterStatus: 'Bereit',
      posterReady: 'Bereit zum Start',
      posterEyebrow: 'DAVINCI AI',
      posterTitle: 'DAVINCI AI x TARA',
      posterLocale: 'DE',
      posterButton: 'Starten',
      posterHint: 'Tippe auf das Poster, um den Sprach-Call zu starten',
      conversation: [
        { from: 'user', label: 'DU', text: 'Was macht Da Vinci AI eigentlich?' },
        { from: 'tara', label: 'TARA', text: 'Wir bauen Enterprise-KI-Infrastruktur für Voice, Memory und souveränen Betrieb.' },
        { from: 'user', label: 'DU', text: 'Und TARA übernimmt die Voice-Seite?' },
        { from: 'tara', label: 'TARA', text: 'Ja. Anrufe, Lead-Qualifizierung, Terminbuchung und Support in Echtzeit.' },
        { from: 'user', label: 'DU', text: 'Ist das DSGVO-konform?' },
        { from: 'tara', label: 'TARA', text: 'Vollständig in der EU gehostet. Kein transatlantischer Datentransfer.' },
      ],
      avgResponse: 'Ø ANTWORTZEIT: 480 ms',
      reasoningTitle: 'Kein Chatbot. Kein Skript.',
      reasoningBody: 'TARA ist der erste Enterprise-Voice-Agent, der schlussfolgert statt nur abzurufen. Während Ihr Kunde noch spricht, verarbeitet TARA parallel vier Ebenen:',
      reasoningPoints: [
        'Was der Nutzer gesagt hat',
        'Was er eigentlich meint',
        'Welches Kernproblem dahinterliegt',
        'Welcher nächste Schritt optimal ist',
      ],
      reasoningFooter: 'Antwort in unter 500 ms. Kaum von einem Menschen zu unterscheiden.',
      variantsLabel: 'Vier Varianten. Eine Intelligenz.',
      variants: [
        { num: '01', title: 'Visueller Co-Pilot', desc: 'Sieht den Bildschirm des Nutzers und führt live durch Formulare, Dashboards und Prozesse.' },
        { num: '02', title: 'Telefonie', desc: 'Ersetzt IVR komplett. Spricht Deutsch nativ. Bucht Termine, löst Tickets und qualifiziert Leads.' },
        { num: '03', title: 'Web-Call', desc: 'Ihre Website spricht. Besucher sprechen direkt im Browser mit TARA. Ohne Telko-Kosten.' },
        { num: '04', title: 'Chat-Assistent', desc: 'Onboardet. Antwortet. Eskaliert. Immer erreichbar. Vergisst nie.' },
      ],
    },
    hivemind: {
      sectionLabel: 'Lösungen / 02',
      topLabel: 'Gedächtnis-Engine',
      metaCode: 'DV-HM002',
      metaSuffix: 'Zweites Gehirn',
      headlineAccent: 'HIVEMIND',
      headlineLines: ['Ihre souveräne', 'Gedächtnis-Engine'],
      subtitle: 'Ihr zweites Gehirn, das nichts vergisst. Verbinden Sie E-Mails, Notizen und Gespräche — und erhalten Sie Monate später exakt die richtige Antwort.',
      primaryCta: 'Kostenlos testen',
      secondaryCta: '87.2% Genauigkeit',
      stats: [
        { val: '<250ms', label: 'Abruf' },
        { val: '87.2%', label: 'LongMemEval Benchmark' },
        { val: '13+', label: 'MCP-Tools' },
      ],
      graphLabel: 'Interaktiv · zum Erkunden bewegen',
      featuresLabel: 'So funktioniert es',
      features: [
        { n: '01', title: 'Es merkt sich alles', desc: 'Jedes Gespräch, jede E-Mail und jedes Dokument — gespeichert, indexiert und verknüpft.', tag: 'Total Recall' },
        { n: '02', title: 'Es verknüpft Zusammenhänge', desc: 'Verwandte Ideen aus Slack, Gmail und Ihren Docs werden automatisch verbunden.', tag: 'Wissensgraph' },
        { n: '03', title: 'Es wird mit der Zeit besser', desc: 'Drei KI-Agenten finden Dubletten, Konflikte und fehlende Verknüpfungen.', tag: 'Selbstlernend' },
        { n: '04', title: 'Ihre Daten bleiben Ihre', desc: 'Gehostet in Frankfurt. DSGVO by design. Keine US-Datentransfers.', tag: 'EU-souverän' },
      ],
      useCasesLabel: 'Für',
      useCasesTitle: 'Für alle, die von Wissen leben',
      useCases: [
        { e: '💼', t: 'Gründer', d: 'Kein Meeting-Insight und kein Investorenfeedback geht verloren.' },
        { e: '🧑‍💻', t: 'Entwickler', d: 'Code-Kontext und Entscheidungen bleiben jederzeit abrufbar.' },
        { e: '📝', t: 'Forscher', d: 'Verbinden Sie Papers, Notizen und Gespräche.' },
        { e: '🏢', t: 'Teams', d: 'Geteiltes Gedächtnis. Wenn jemand geht, bleibt das Wissen.' },
      ],
      footerLeft: 'HIVEMIND Gedächtnis-Engine',
      footerRight: 'EU-souverän · DSGVO-nativ',
    },
    enterprise: {
      sectionLabel: 'Lösungen / 03',
      title: ['Enterprise-', 'Bereitstellung'],
      subtitle: 'Stellen Sie souveräne KI-Infrastruktur zu Ihren Bedingungen bereit. Volle Kontrolle über Datenstandort, Compliance und operative Richtlinien mit der Managed Platform von Da Vinci.',
      features: [
        { title: 'Souveränes Hosting', desc: 'EU-Rechenzentren, von Grund auf DSGVO-konform' },
        { title: 'Individuelle Integration', desc: 'Verbinden Sie Ihre bestehenden Tools und Workflows' },
        { title: 'Managed Platform', desc: 'Wir betreiben die Infrastruktur, Sie treiben die Innovation' },
      ],
      compliance: ['SOC 2-konform', 'EU-Datenresidenz', 'Ende-zu-Ende-Verschlüsselung'],
    },
    brand: {
      background: ['MARKE', 'STIMME'],
      tagline: 'Ihre digitale Präsenz, verstärkt.',
      title: 'TARA.',
      description: 'Ihre erste Mitarbeiterin für Ihre Marke. Sie spricht, qualifiziert und konvertiert — in Ihrer Stimme, über Web, Calls und Video.',
      cta: 'Gespräch starten',
      footer: ['WEB', 'SPRACHE', 'VIDEO'],
    },
    research: {
      label: 'Forschung',
      title: ['Kognitive Schwarm-', 'Intelligenz'],
      quote: '"Das System erinnert sich. Die Agenten handeln nur."',
      citation: '— DavinciAI Labs, CSI Paper 2026',
      body: 'Wir haben die Architektur hinter HIVEMIND veröffentlicht. CSI beschreibt umgebungszentrierte Intelligenz — bei der Gedächtnis, Verhalten und Richtlinien in ein gemeinsames kognitives Substrat ausgelagert werden.',
      cta: 'Paper lesen',
    },
    about: {
      label: 'Kontakt',
      title: 'Kontakt aufnehmen',
      body: 'Sie haben eine Frage, eine Partnerschaftsanfrage oder möchten einfach Hallo sagen? Wir freuen uns auf Ihre Nachricht.',
      email: 'E-Mail',
      locationLabel: 'Standort',
      location: 'Hannover, Deutschland',
      cta: 'Nachricht senden',
      footer: "Da'Vinci Solutions / 2026",
    },
  },
};

export const getMobileCopy = (locale = 'en') => mobileCopy[locale] || mobileCopy.en;
